name: Release pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Publish release to CDN
    runs-on: ubuntu-latest
    env:
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
    steps:
      - name: Clone project
        uses: actions/checkout@v4
      - name: Prepare package
        run: |
          zip -9 -r tukui-$VERSION.zip Tukui
      - name: Publish package
        run: |
          curl https://api.tukui.org/v1/upload/tukui-$GITHUB_REF_NAME.zip --upload-file tukui-$GITHUB_REF_NAME.zip -H "X-Tukui-Key: $DEPLOY_KEY" -H "Content-Type: application/zip"
